name: Gradle 部署

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: 构建
    runs-on: ubuntu-latest

    steps:
      - name: 取得 Github 仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 取得 Gradle 缓存
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 建立 JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: 17

      - name: 验证 Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: 通过 Gradle 部署
        run: |
          chmod +x gradlew
          ./gradlew build --stacktrace

      - name: 安装“重命名”
        run: sudo apt-get install -y rename

      - name: 重命名文件
        run: |
          cd ./build/libs/
          rename -f 's/-all//;' '' *

      - name: 通过 Github 存档 jar 文件
        uses: actions/upload-artifact@v3
        with:
          name: xaero-map-spigot
          path: build/libs
